{{ if .Values.secret.create -}}
---
apiVersion: v1
data:
  admin: {{ .Values.secret.admin }}
  token: {{ .Values.secret.token }}
kind: Secret
metadata:
  labels:
    {{- include "alertmanager-bot.labels" . | nindent 4 }}
  name: {{ include "alertmanager-bot.fullname" . }}
type: Opaque
{{ end }}
